name = "Spinach"
uuid = "8ce1c32a-6c7d-48a0-a319-84c3247a853e"
authors = ["Gabriel Baraldi <baraldigabriel@gmail.com> and contributors"]
version = "0.1.0"

[deps]
LLVM = "929cbde3-209d-540e-8aea-75f648917ca0"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
LLVM = "4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
